---
- name: Install RabbitMQ prerequisites and repositories
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Import Team RabbitMQ's main signing key
      ansible.builtin.shell: |
        curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | gpg --dearmor | tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null

    - name: Import RabbitMQ Erlang repository signing key
      ansible.builtin.shell: |
        curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | gpg --dearmor | tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null

    - name: Import RabbitMQ server repository signing key
      ansible.builtin.shell: |
        curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | gpg --dearmor | tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null

    - name: Add RabbitMQ apt repositories
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/rabbitmq.list
        content: |
          ## Provides modern Erlang/OTP releases
          ##
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main

          # another mirror for redundancy
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main

          ## Provides RabbitMQ
          ##
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy main

          # another mirror for redundancy
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy main

- name: Install RabbitMQ and Erlang
  hosts: all
  become: true
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Update if the cache is older than an hour

    - name: Install Erlang packages
      apt:
        name:
          - erlang-base
          - erlang-asn1
          - erlang-crypto
          - erlang-eldap
          - erlang-ftp
          - erlang-inets
          - erlang-mnesia
          - erlang-os-mon
          - erlang-parsetools
          - erlang-public-key
          - erlang-runtime-tools
          - erlang-snmp
          - erlang-ssl
          - erlang-syntax-tools
          - erlang-tftp
          - erlang-tools
          - erlang-xmerl
        state: present
        update_cache: yes


- name: Install Erlang dependencies (Bionic)
  block:
    - name: Install Team RabbitMQ's main signing key
      apt_key:
        url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
        state: present
    - name: Install Community mirror of Cloudsmith modern Erlang repository key
      apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
        state: present
    - name: Install Community mirror of Cloudsmith RabbitMQ repository key
      apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
        state: present

    - name: Add Erlang Solutions repository
      apt_repository:
        repo: 'deb http://packages.erlang-solutions.com/ubuntu {{ ansible_distribution_release|lower }} contrib'
        state: present

    - name: Install Erlang packages
      apt:
        name: "esl-erlang={{ erlang }}"
        update_cache: yes
        force: yes
      register: rabbitmq_erlang_apt_install_result
      ignore_errors: true

    - name: Install Erlang dependencies (alternate method)
      apt:
        deb: "https://packages.erlang-solutions.com/ubuntu/pool/esl-erlang_{{ erlang | regex_replace('^[0-9]+:(.*)$', '\\1') }}~ubuntu~bionic_amd64.deb"
        force: yes
      when: rabbitmq_erlang_apt_install_result is failed
  when: ansible_distribution_version == '18.04'

- name: Install Erlang dependencies (Jammy)
  apt:
    name: erlang
    state: present
  when: ansible_distribution_version == '22.04'

- name: Add trusted key
  apt_key:
    url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    state: present

- name: Add rabbitmq official apt repository
  apt_repository:
    repo: 'deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu {{ ansible_distribution_release|lower }} main'
    state: present
    update_cache: yes

- name: Install package
  apt:
    name: "rabbitmq-server={{ rabbitmq_version }}"
    update_cache: yes
    state: present
  ignore_errors: '{{ ansible_check_mode }}'

- name: Enable rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_tracing,rabbitmq_federation
    state: enabled
  notify:
    - restart rabbitmq
