---
- name: Install Java
  become: yes
  apt:
    name: "{{ java_packages }}"

- name: Correct java version selected
  alternatives:
    name: java
    path: "{{ java_bin_path }}/java"

- name: Check the Java version
  command: java -version
  changed_when: false
  register: java_version

- name: Display the Java version.
  debug:
    var: java_version
    verbosity: 2

- name: Ensure the required MBeanTrustPermission is present in the java.policy file  #BKA
  ansible.builtin.lineinfile:
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.policy  # Adjust to the correct path
    line: 'permission javax.management.MBeanTrustPermission "register";'
    insertafter: 'grant {'
    state: present

- name: Ensure the required MBeanServerPermission is present in the java.policy file
  lineinfile:
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.policy  # Adjust to the correct path
    line: 'permission javax.management.MBeanServerPermission "createMBeanServer";'
    insertafter: 'grant {'
    state: present
