# This role is declared as a dependency in common_installs/meta/main.yml.
# It allows all other roles to use the latest setuptools and pip
# executable for Python 3.6. This is the version of Python that Ansible
# is running on, and Ansible's default pip executable.
---

- name: Install Python packages
  become: yes
  apt:
    name:
      - python3-pip  # Creates /usr/bin/pip3
      - python3-dev
      - python3-setuptools

- name: Update pip & setuptools
  become: yes
  pip:
    name:
      - pip  # Creates/updates /usr/local/bin/pip
      - setuptools
    state: latest
    executable: pip3  # Use /usr/bin/pip3 this time only

